# Generated by Django 4.0.2 on 2022-04-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_listening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listening',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='listening',
            name='date',
            field=models.DateField(verbose_name='listening date'),
        ),
        migrations.AddField(
            model_name='album',
            name='formats',
            field=models.ManyToManyField(to='main_app.Format'),
        ),
    ]
